<a href="https://colab.research.google.com/github/douglasbarbosadelima/Data-Science/blob/master/3modelos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==2.0.0 

     |████████████████████████████████| 86.3MB 73kB/s 
     |████████████████████████████████| 3.8MB 43.5MB/s 
     |████████████████████████████████| 450kB 58.8MB/s 
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalled tensorflow-1.15.0


In [2]:
import tensorflow as tf
import math
import numpy as np
import random
tf.__version__

'2.0.0'

Agora vamos criar sequências de 3 inteiros, começando com um a 15 deltas. O target será o quarto inteiro

In [3]:
X=[]
y=[]
random.seed(42)
for i in range(100):
  ini=random.randint(1,15)
  seq=[]
  for j in range(4):
    seq.append([ini+j])
  X.append(seq)
  y.append([ini+4])
X=np.array(X)
y=np.array(y)

X[:3],y[:3]


(array([[[11],
         [12],
         [13],
         [14]],
 
        [[ 2],
         [ 3],
         [ 4],
         [ 5]],
 
        [[ 1],
         [ 2],
         [ 3],
         [ 4]]]), array([[15],
        [ 6],
        [ 5]]))

Modelo 1 : RNN com memória no Output

In [0]:
tf.random.set_seed(51)
model1=tf.keras.Sequential()
model1.add(tf.keras.layers.SimpleRNN(1,input_shape=(None,1),activation=lambda x:x))

In [0]:
model1.compile(loss='mean_squared_error', optimizer='adam')

In [6]:
model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [7]:
model1.fit(X, y, epochs=300)

Train on 100 samples
Epoch 1/300
100/100 [==============================] - 1s 8ms/sample - loss: 133.7196
Epoch 2/300
100/100 [==============================] - 0s 106us/sample - loss: 133.1064
Epoch 3/300
100/100 [==============================] - 0s 111us/sample - loss: 132.4483
Epoch 4/300
100/100 [==============================] - 0s 110us/sample - loss: 131.8340
Epoch 5/300
100/100 [==============================] - 0s 100us/sample - loss: 131.1686
Epoch 6/300
100/100 [==============================] - 0s 117us/sample - loss: 130.4943
Epoch 7/300
100/100 [==============================] - 0s 105us/sample - loss: 129.8114
Epoch 8/300
100/100 [==============================] - 0s 102us/sample - loss: 129.1366
Epoch 9/300
100/100 [==============================] - 0s 105us/sample - loss: 128.4180
Epoch 10/300
100/100 [==============================] - 0s 94us/sample - loss: 127.6637
Epoch 11/300
100/100 [==============================] - 0s 128us/sample - loss: 126.9293
Epoch 12/300

In [13]:
w=model1.get_weights()
w

[array([[1.2152089]], dtype=float32),
 array([[-0.2592902]], dtype=float32),
 array([1.0703976], dtype=float32)]

In [14]:
model1.predict([[[1.0],[2.0],[3.0],[4.0]]])

array([[4.9039354]], dtype=float32)

Modelo 2 : LSTM com ativação identidade

In [0]:
tf.random.set_seed(51)
model2=tf.keras.Sequential()
model2.add(tf.keras.layers.LSTM(1,input_shape=(None,1),activation=lambda x:x))

In [0]:
model2.compile(loss='mean_squared_error', optimizer='adam')

In [17]:
model2.fit(X, y, epochs=300)

Train on 100 samples
Epoch 1/300
100/100 [==============================] - 1s 10ms/sample - loss: 20.8644
Epoch 2/300
100/100 [==============================] - 0s 150us/sample - loss: 18.3647
Epoch 3/300
100/100 [==============================] - 0s 147us/sample - loss: 16.0866
Epoch 4/300
100/100 [==============================] - 0s 127us/sample - loss: 14.2527
Epoch 5/300
100/100 [==============================] - 0s 124us/sample - loss: 12.5541
Epoch 6/300
100/100 [==============================] - 0s 123us/sample - loss: 11.0774
Epoch 7/300
100/100 [==============================] - 0s 142us/sample - loss: 9.8138
Epoch 8/300
100/100 [==============================] - 0s 118us/sample - loss: 8.7127
Epoch 9/300
100/100 [==============================] - 0s 145us/sample - loss: 7.7332
Epoch 10/300
100/100 [==============================] - 0s 145us/sample - loss: 6.8451
Epoch 11/300
100/100 [==============================] - 0s 142us/sample - loss: 6.0905
Epoch 12/300
100/100 [====

In [18]:
w=model2.get_weights()
w
#ordem dos pesos input, recorrência e bias
#em cada vetor i,f,c,o

[array([[ 0.23591968, -0.07393049,  0.9296858 ,  0.3007333 ]],
       dtype=float32),
 array([[-0.34371743,  0.5863273 , -0.6087364 ,  1.0324925 ]],
       dtype=float32),
 array([ 0.25976655,  1.2502346 ,  0.40401053, -1.03383   ], dtype=float32)]

In [19]:
ww,wu,wb=w
ww,wu,wb

(array([[ 0.23591968, -0.07393049,  0.9296858 ,  0.3007333 ]],
       dtype=float32),
 array([[-0.34371743,  0.5863273 , -0.6087364 ,  1.0324925 ]],
       dtype=float32),
 array([ 0.25976655,  1.2502346 ,  0.40401053, -1.03383   ], dtype=float32))

In [20]:
model2.predict([[[1.0],[2.0],[3.0],[4.0]]])

array([[4.3773975]], dtype=float32)

Modelo 3 : ANN com um neurônio e ativação identidade

In [21]:
#mudança para compatibilizar o input na ANN (o perceptron recebe os 4 inputs no mesmo t)
X3=X.reshape((100,1,4))
X3[:2]

array([[[11, 12, 13, 14]],

       [[ 2,  3,  4,  5]]])

In [0]:
tf.random.set_seed(51)
model3=tf.keras.Sequential()
model3.add(tf.keras.layers.Dense(1,input_shape=(1,4),activation=lambda x:x))

In [0]:
model3.compile(loss='mean_squared_error', optimizer='adam')

In [24]:
model3.fit(X3, y, epochs=300)

Train on 100 samples
Epoch 1/300
100/100 [==============================] - 0s 3ms/sample - loss: 6.6122
Epoch 2/300
100/100 [==============================] - 0s 102us/sample - loss: 5.8858
Epoch 3/300
100/100 [==============================] - 0s 111us/sample - loss: 5.1606
Epoch 4/300
100/100 [==============================] - 0s 94us/sample - loss: 4.5695
Epoch 5/300
100/100 [==============================] - 0s 89us/sample - loss: 3.9733
Epoch 6/300
100/100 [==============================] - 0s 93us/sample - loss: 3.4344
Epoch 7/300
100/100 [==============================] - 0s 88us/sample - loss: 2.9528
Epoch 8/300
100/100 [==============================] - 0s 89us/sample - loss: 2.5477
Epoch 9/300
100/100 [==============================] - 0s 88us/sample - loss: 2.1599
Epoch 10/300
100/100 [==============================] - 0s 89us/sample - loss: 1.8105
Epoch 11/300
100/100 [==============================] - 0s 84us/sample - loss: 1.5296
Epoch 12/300
100/100 [===================

In [25]:
model3.get_weights()

[array([[ 0.03229318],
        [-0.31357273],
        [ 0.70251966],
        [ 0.63701695]], dtype=float32), array([0.44083115], dtype=float32)]

In [26]:
model3.predict([[[1.0,2.0,3.0,4.0]]])

array([[[4.501606]]], dtype=float32)