<a href="https://colab.research.google.com/github/douglasbarbosadelima/Data-Science/blob/master/Backpropag.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Backpropagation

In [0]:
"""

Linked Education

Backpropagation XOR  saída linear (identidade)
hidden layer: 2 perceptrons com
ativação sigmoid

Código complementa planilha ANN-backprop.xlsm

Código adaptado de :
https://brilliant.org/wiki/backpropagation/

Atividade 1 : analisar código

Atividade 2: comparar resultados com a planilha ANN-backprop.xlsm

Atividade 3 : criar função custo (erro médio quadrático)
e traçar gáfico : iterações x custo

Atividade 4: inicializar com pesos randômicos (semente fixa)
e verificar número de iterações até a convergência


@author: Linked
"""

import numpy as np
import matplotlib.pyplot as plt

In [0]:


#função custo

def cost(ye,y):
    diff = ye - y
    return (1 / (2 *len(y))) * np.inner(diff, diff)

# sigmoid 
def sigmoid(x, derivative=False):

    if (derivative == True):
        return x * (1 - x)
    else:
        return 1 / (1 + np.exp(-x))

# pesos randômicos fixos..não utlizados
#np.random.seed(1)

# learning rate
alpha = .1 

# nós na camada hidden
num_hidden = 2

# inputs
X = np.array([  
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
  
])


y = np.array([[0, 1, 1, 0]]).T



hidden_weights=np.array([[0.1,  0.4],
[0.6,  0.2],
[0.3, 0.8]
])


output_weights=np.array([[0.2],[0.9],[0.7]])

# número de iterações : Gradient Descent
num_iterations = 1 

costs=[]





In [16]:
for i in range(num_iterations):

    # fase forward: obtem os outputs de todas as camadas
    # cria uma coluna de 1 (np.stack) no X (bias)
    input_layer_outputs = np.hstack((np.ones((X.shape[0], 1)), X))
    hidden_layer_outputs = np.hstack((np.ones((X.shape[0], 1)), sigmoid(np.dot(input_layer_outputs, hidden_weights))))
    output_layer_outputs = np.dot(hidden_layer_outputs, output_weights)

    costs.append(cost(output_layer_outputs.reshape((4,)),y.reshape((4,))))  
    # backward phase
    # Erro Output 
    output_error = output_layer_outputs - y
    # 
    # Bias não entra no cálculo
    hidden_error = hidden_layer_outputs[:, 1:] * (1 - hidden_layer_outputs[:, 1:]) * np.dot(output_error, output_weights.T[:, 1:])

    # Gradiente acumulado       
    hidden_pd = input_layer_outputs[:, :, np.newaxis] * hidden_error[: , np.newaxis, :]
    output_pd = hidden_layer_outputs[:, :, np.newaxis] * output_error[:, np.newaxis, :]

    # Gradiente médio (final)
    total_hidden_gradient = np.average(hidden_pd, axis=0)
    total_output_gradient = np.average(output_pd, axis=0)

    # update weights
    hidden_weights += - alpha * total_hidden_gradient
    output_weights += - alpha * total_output_gradient

print(
    'total_hidden_gradient:\n', total_hidden_gradient, 
    '\n\ntotal_output_gradient:\n', total_output_gradient, 
    '\n\nhidden_weights:\n', hidden_weights, 
    '\n\noutput_weights:\n', output_weights)

total_hidden_gradient:
 [[0.15164181 0.10407359]
 [0.07543196 0.04956137]
 [0.07775727 0.04803558]] 

total_output_gradient:
 [[0.76028968]
 [0.4864378 ]
 [0.5421176 ]] 

hidden_weights:
 [[0.08483582 0.38959264]
 [0.5924568  0.19504386]
 [0.29222427 0.79519644]] 

output_weights:
 [[0.12397103]
 [0.85135622]
 [0.64578824]]
