<a href="https://colab.research.google.com/github/douglasbarbosadelima/Data-Science/blob/master/bow_repeat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bag of words, conceitos básicos + tf*idf

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import math
import numpy as np
texto = [
        "O cavalo foi encontrado próximo à fazenda na fazenda com fazenda",
        "Os donos se assustaram com a polícia na fazenda",
        "Os ladrões já conheciam a região"
        ]

vectorizer = CountVectorizer(stop_words=['o','se','na','a','os','já','com','à'])
vectorizer.fit(texto)
print(vectorizer.vocabulary_)
vector = vectorizer.transform(texto)#transforma em vetores encoded para "sparse"
print('O tipo de vector é ',type(vector))
print(vector.shape)
print(vector.toarray()) #Check occurrency numbers // [0 1 0 0 1 *** 3 *** 1 0 0 1 0]

{'cavalo': 1, 'foi': 6, 'encontrado': 4, 'próximo': 9, 'fazenda': 5, 'donos': 3, 'assustaram': 0, 'polícia': 8, 'ladrões': 7, 'conheciam': 2, 'região': 10}
O tipo de vector é  <class 'scipy.sparse.csr.csr_matrix'>
(3, 11)
[[0 1 0 0 1 3 1 0 0 1 0]
 [1 0 0 1 0 1 0 0 1 0 0]
 [0 0 1 0 0 0 0 1 0 0 1]]


In [5]:
nova_amostra=["É uma região de cavalo,cavalo e fazenda, fazendas"]
v2=vectorizer.transform(nova_amostra)#observe a falta do stemming, "fazenda" e "fazendas" são palavras distintas.
print(v2.toarray())

[[0 2 0 0 0 1 0 0 0 0 1]]


In [6]:
#Agora será feita uma versão de encoding com tfidf (Mensurador de palavras "chave" em um contexto(palavras).)
vect2 = TfidfVectorizer(stop_words=['o','se','na','a','os','já','com','à'],norm=None,smooth_idf=False)
vect2.fit(texto)
print(vect2.vocabulary_)
v2 = vect2.transform(texto)#transforma em vetores encoded para  "sparse"
print('O tipo de vector é ',type(v2))
print(v2.toarray())


{'cavalo': 1, 'foi': 6, 'encontrado': 4, 'próximo': 9, 'fazenda': 5, 'donos': 3, 'assustaram': 0, 'polícia': 8, 'ladrões': 7, 'conheciam': 2, 'região': 10}
O tipo de vector é  <class 'scipy.sparse.csr.csr_matrix'>
[[0.         2.09861229 0.         0.         2.09861229 4.21639532
  2.09861229 0.         0.         2.09861229 0.        ]
 [2.09861229 0.         0.         2.09861229 0.         1.40546511
  0.         0.         2.09861229 0.         0.        ]
 [0.         0.         2.09861229 0.         0.         0.
  0.         2.09861229 0.         0.         2.09861229]]


In [7]:
v3=vect2.transform(nova_amostra)
v3a=v3.toarray()
print(v3a)


[[0.         4.19722458 0.         0.         0.         1.40546511
  0.         0.         0.         0.         2.09861229]]


In [0]:
#Mostre na mão o cálculo do tf-idf