<a href="https://colab.research.google.com/github/douglasbarbosadelima/Data-Science/blob/master/CNN_series_res.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==2.0.0 

     |████████████████████████████████| 86.3MB 70kB/s 
     |████████████████████████████████| 450kB 51.1MB/s 
     |████████████████████████████████| 3.8MB 49.2MB/s 
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalled tensorflow-1.15.0


In [2]:
import tensorflow as tf
import math
import numpy as np
import random
tf.__version__

'2.0.0'

Agora vamos criar sequências de 3 inteiros, começando com um a 15 deltas. O target será o quarto inteiro

In [3]:
X=[]
y=[]
random.seed(42)
for i in range(100):
  ini=random.randint(1,15)
  seq=[]
  for j in range(3):
    seq.append(ini+j)
  X.append(seq)
  y.append([ini+3])
X=np.array(X)
X=X[:,:,np.newaxis]

y=np.array(y)

X[:3],y[:3]


(array([[[11],
         [12],
         [13]],
 
        [[ 2],
         [ 3],
         [ 4]],
 
        [[ 1],
         [ 2],
         [ 3]]]), array([[14],
        [ 5],
        [ 4]]))

CNN 1D com 1 filtro de tamanho 2 + Dense(1)

In [0]:
tf.random.set_seed(51)
model1=tf.keras.Sequential()
model1.add(tf.keras.layers.Conv1D(1,kernel_size=2,input_shape=(None,1),use_bias=False))
model1.add(tf.keras.layers.MaxPooling1D(pool_size=2))
model1.add(tf.keras.layers.Dense(1))

In [0]:
model1.compile(loss='mean_squared_error', optimizer='adam')

In [6]:
model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, None, 1)           2         
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, None, 1)           0         
_________________________________________________________________
dense (Dense)                (None, None, 1)           2         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [7]:
model1.fit(X, y, epochs=300)

Train on 100 samples
Epoch 1/300
100/100 [==============================] - 1s 6ms/sample - loss: 134.8757
Epoch 2/300
100/100 [==============================] - 0s 98us/sample - loss: 133.2442
Epoch 3/300
100/100 [==============================] - 0s 83us/sample - loss: 131.5350
Epoch 4/300
100/100 [==============================] - 0s 93us/sample - loss: 130.0009
Epoch 5/300
100/100 [==============================] - 0s 100us/sample - loss: 128.2560
Epoch 6/300
100/100 [==============================] - 0s 100us/sample - loss: 126.4795
Epoch 7/300
100/100 [==============================] - 0s 95us/sample - loss: 124.7225
Epoch 8/300
100/100 [==============================] - 0s 79us/sample - loss: 123.0353
Epoch 9/300
100/100 [==============================] - 0s 90us/sample - loss: 121.2771
Epoch 10/300
100/100 [==============================] - 0s 98us/sample - loss: 119.4726
Epoch 11/300
100/100 [==============================] - 0s 101us/sample - loss: 117.7532
Epoch 12/300
100/1

In [8]:
w=model1.get_weights()
w

[array([[[0.591549  ]],
 
        [[0.15024267]]], dtype=float32),
 array([[1.5245993]], dtype=float32),
 array([0.39320806], dtype=float32)]

In [11]:
model1.predict([[[1.0],[2.0],[3.0]]])

array([[[2.884138]]], dtype=float32)

In [0]:
#Fazendo a convolução na mão para 1,2,3,4...
series=[[1,2],[2,3]]
kernel=[0.591549 ,0.15024267]
conv1=[np.inner(kernel,s) for s in series]
conv1


In [0]:
model2=tf.keras.Sequential()
model2.add(model1.layers[0])

In [14]:
model2.predict(X[2:3])

array([[[0.8920343],
        [1.633826 ]]], dtype=float32)

In [15]:
#Agora, conferindo o maxpooling
model3=tf.keras.Sequential()
model3.add(model1.layers[0])
model3.add(model1.layers[1])
model3.predict(X[2:3])

array([[[1.633826]]], dtype=float32)

In [16]:
#E o output final
1.633826*1.5245993+0.39320806

2.8841380359218