<a href="https://colab.research.google.com/github/douglasbarbosadelima/Data-Science/blob/master/cnn_raiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow-gpu==2.0.0 #com GPU

     |████████████████████████████████| 380.8MB 43kB/s 
     |████████████████████████████████| 450kB 50.1MB/s 
     |████████████████████████████████| 3.8MB 53.9MB/s 
ERROR: tensorflow 1.15.0 has requirement tensorboard<1.16.0,>=1.15.0, but you'll have tensorboard 2.0.2 which is incompatible.
ERROR: tensorflow 1.15.0 has requirement tensorflow-estimator==1.15.1, but you'll have tensorflow-estimator 2.0.1 which is incompatible.
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0


In [2]:
import tensorflow as tf
import numpy as np
import random
tf.random.set_seed(42)
print(tf.__version__)

2.0.0


In [5]:
#imagem 28x28 com valores entre o e 255
img=np.zeros((784,))
random.seed(42)
for i in range(len(img)):
  img[i]=random.randint(0,255)
img=img.reshape((28,28))
kernel=np.array([[0,1,0],[0,1,0],[0,1,0]])#definição do filtro 3x3
img[:4,:4]

array([[ 57.,  12., 140., 125.],
       [ 52.,  47., 194.,  49.],
       [181., 107., 136.,  36.],
       [126., 134., 219., 204.]])

In [0]:
def conv(m,k):
  #crie a função convolução entre 2 matrizes (é só uma linha)
  return (m*k).sum()

In [9]:
conv(img[:3,:3],kernel)

166.0

In [10]:
#nosso filtro é 3x3 e o stride é 1, só pegando partes válidas da imagem(?)
#qual vai se a dimensão da imagem apõs a convolução? Como manter
#a dimensão original?
m,n=img.shape
mk,nk=kernel.shape
img_conv=np.zeros((m-mk+1, n-nk+1))
img_conv.shape

(26, 26)

In [14]:
mc,nc=img_conv.shape
for i in range(mc):
  for j in range(nc):
    img_conv[i,j]=conv(img[i:i+3, j:j+3],kernel)#qual é o pedaço da matriz?
img_conv[:4, :4]

array([[166., 470., 210., 384.],
       [288., 549., 289., 455.],
       [375., 446., 294., 424.],
       [376., 412., 417., 541.]])

In [0]:
def relu_mat(X):
  m,n = X.shape
  X = X.reshape((m*n, ))
  for i in range(len(X)):
    if X[i] < 0: X[i] = 0
  return X.reshape((m,n))


In [27]:
img_conv=relu_mat(img_conv)
img_conv

array([[166., 470., 210., 384., 372., 270., 302., 645., 217., 320., 253.,
        289., 421., 127., 297., 442., 365., 410., 290., 283., 240., 665.,
        518., 608., 338., 328.],
       [288., 549., 289., 455., 413., 288., 510., 475., 225., 361., 284.,
        259., 518., 146., 393., 423., 492., 309., 153., 338., 295., 623.,
        401., 616., 481., 298.],
       [375., 446., 294., 424., 338., 231., 679., 322., 162., 333., 494.,
        118., 390., 233., 515., 522., 405., 284., 153., 262., 492., 464.,
        323., 449., 538., 299.],
       [376., 412., 417., 541., 404., 372., 674., 189., 150., 336., 360.,
        263., 283., 334., 466., 320., 304., 281., 162., 135., 400., 378.,
        157., 336., 607., 412.],
       [484., 317., 455., 564., 389., 350., 471., 363., 307., 496., 492.,
        421.,  94., 352., 300., 331., 238., 208., 284., 175., 361., 433.,
        171., 402., 478., 474.],
       [388., 452., 451., 437., 295., 319., 401., 366., 515., 579., 488.,
        521., 242., 1

In [0]:
def max_pool(M):
  m,n = M.shape
  M = M.reshape((m*n, ))
  return M.max()

In [0]:
mc,nc=img_conv.shape
mpool,npool=2,2 #pooling size, stride 2
pooled=np.zeros((mc//mpool, nc//npool))
pl,pc=pooled.shape

In [0]:
for i in range(pl):
  for j in range(pc):
    pooled[i,j]=max_pool(img_conv[mpool * i : mpool * i + 2, npool * j : npool * j + 2])

In [36]:
pooled

array([[549., 455., 413., 645., 361., 289., 518., 442., 492., 338., 665.,
        616., 481.],
       [446., 541., 404., 679., 336., 494., 390., 522., 405., 262., 492.,
        449., 607.],
       [484., 564., 389., 471., 579., 521., 352., 403., 284., 379., 614.,
        416., 541.],
       [510., 321., 348., 346., 499., 490., 600., 438., 468., 463., 605.,
        442., 392.],
       [522., 591., 423., 559., 321., 415., 466., 620., 582., 371., 348.,
        370., 501.],
       [517., 432., 476., 566., 326., 464., 589., 529., 519., 370., 525.,
        538., 445.],
       [577., 543., 666., 358., 432., 482., 604., 533., 305., 667., 563.,
        579., 596.],
       [420., 637., 387., 530., 457., 483., 613., 535., 667., 578., 561.,
        541., 562.],
       [577., 614., 417., 511., 457., 510., 486., 293., 565., 402., 499.,
        550., 653.],
       [447., 491., 510., 572., 619., 445., 432., 505., 505., 684., 484.,
        663., 633.],
       [440., 429., 586., 734., 557., 397., 531., 