<a href="https://colab.research.google.com/github/douglasbarbosadelima/Data-Science/blob/master/cnn_ox.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 Cnn para OX

In [1]:
!pip install tensorflow-gpu==2.0.0 

     |████████████████████████████████| 380.8MB 47kB/s 
     |████████████████████████████████| 3.8MB 28.7MB/s 
     |████████████████████████████████| 450kB 36.2MB/s 
ERROR: tensorflow 1.15.0 has requirement tensorboard<1.16.0,>=1.15.0, but you'll have tensorboard 2.0.2 which is incompatible.
ERROR: tensorflow 1.15.0 has requirement tensorflow-estimator==1.15.1, but you'll have tensorflow-estimator 2.0.1 which is incompatible.
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1


In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
tf.__version__

'2.0.0'

Carregamento do Dataset (as pastas o1 e x1 devem estar na /content)

In [0]:
import os

def list_files(path,ini):
    l=[]
    for name in os.listdir(path):
        if name[0]==ini:l.append(name)
    return l
lo1=list_files('/content/o1','o')
lx1=list_files('/content/x1','x')

In [0]:
Xtn=[]
ytn=[]
patho='/content/o1/'
for arq in lo1:
  img=plt.imread(patho+arq)
  Xtn.append(img)
  ytn.append([0])
pathx='/content/x1/'
for arq in lx1:
  img=plt.imread(pathx+arq) 
  Xtn.append(img)
  ytn.append([1])
             
Xtn=np.array(Xtn)
ytn = tf.keras.utils.to_categorical(ytn)

In [0]:
model=tf.keras.Sequential()
model.add(tf.keras.layers.Convolution2D(30,kernel_size=3, activation='relu', input_shape=(224,224,3),use_bias=False))
model.add(tf.keras.layers.MaxPool2D(pool_size=(2, 2)))
model.add(tf.keras.layers.Convolution2D(30,kernel_size=3, activation='relu',use_bias=False))
model.add(tf.keras.layers.MaxPool2D(pool_size=(2, 2)))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(40, activation='relu'))
model.add(tf.keras.layers.Dense(20, activation='relu'))
model.add(tf.keras.layers.Dense(2, activation='softmax'))


In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 222, 222, 30)      810       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 111, 111, 30)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 109, 109, 30)      8100      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 54, 54, 30)        0         
_________________________________________________________________
flatten (Flatten)            (None, 87480)             0         
_________________________________________________________________
dense (Dense)                (None, 40)                3499240   
_________________________________________________________________
dense_1 (Dense)              (None, 20)                8

In [0]:
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

In [8]:
hist=model.fit(Xtn, ytn, epochs=50)

Train on 20 samples
Epoch 1/50
20/20 [==============================] - 7s 369ms/sample - loss: 0.6942 - accuracy: 0.4500
Epoch 2/50
20/20 [==============================] - 0s 1ms/sample - loss: 0.6447 - accuracy: 0.8500
Epoch 3/50
20/20 [==============================] - 0s 1ms/sample - loss: 0.6074 - accuracy: 1.0000
Epoch 4/50
20/20 [==============================] - 0s 1ms/sample - loss: 0.5733 - accuracy: 1.0000
Epoch 5/50
20/20 [==============================] - 0s 1ms/sample - loss: 0.5427 - accuracy: 1.0000
Epoch 6/50
20/20 [==============================] - 0s 1ms/sample - loss: 0.5090 - accuracy: 1.0000
Epoch 7/50
20/20 [==============================] - 0s 1ms/sample - loss: 0.4731 - accuracy: 1.0000
Epoch 8/50
20/20 [==============================] - 0s 1ms/sample - loss: 0.4371 - accuracy: 1.0000
Epoch 9/50
20/20 [==============================] - 0s 1ms/sample - loss: 0.4023 - accuracy: 1.0000
Epoch 10/50
20/20 [==============================] - 0s 1ms/sample - loss: 0.3

In [9]:
from keras.preprocessing import image
img_path = '/content/oxteste/xt1.png'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
#x=tf.keras.applications.mobilenet_v2.preprocess_input(x)
preds = model.predict(x)
preds


Using TensorFlow backend.


array([[0., 1.]], dtype=float32)

In [10]:
lto=list_files('/content/oxteste','o')
ltx=list_files('/content/oxteste','x')
certos=0
for arq in lto:
  img_path = '/content/oxteste/'+arq
  img = image.load_img(img_path, target_size=(224, 224))
  x = image.img_to_array(img)
  x = np.expand_dims(x, axis=0)
  #x=tf.keras.applications.mobilenet_v2.preprocess_input(x)
  preds = model.predict(x)
  print(preds,arq)
  if preds[0][0]>preds[0][1]:certos+=1
for arq in ltx:
  img_path = '/content/oxteste/'+arq
  img = image.load_img(img_path, target_size=(224, 224))
  x = image.img_to_array(img)
  x = np.expand_dims(x, axis=0)
  #x=tf.keras.applications.mobilenet_v2.preprocess_input(x)
  preds = model.predict(x)
  print(preds,arq)
  if preds[0][1]>preds[0][0]:certos+=1
print(certos/(len(lto)+len(ltx)))

[[1. 0.]] ot.png
[[0. 1.]] ot2.png
[[1. 0.]] ot1.png
[[1. 0.]] ot4.png
[[1. 0.]] ot3.png
[[0. 1.]] xt3.png
[[0. 1.]] xt5.png
[[0. 1.]] xt1.png
[[0. 1.]] xt2.png
[[0. 1.]] xt4.png
[[0. 1.]] xt.png
0.9090909090909091
