<a href="https://colab.research.google.com/github/douglasbarbosadelima/Data-Science/blob/master/Deep_bow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Deep Bow : classificação de polaridade com base reduzida do yelp (10k)

In [1]:
!pip install tensorflow==2.0.0 

     |████████████████████████████████| 86.3MB 75kB/s 
     |████████████████████████████████| 3.8MB 59.6MB/s 
     |████████████████████████████████| 450kB 50.0MB/s 
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalled tensorflow-1.15.0


In [0]:
import tensorflow as tf
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
import pandas as pd
import numpy as np
import random

In [29]:
df=pd.read_csv('yelp_short_10k.csv')
df.head()

Unnamed: 0               review_id  ... funny cool
0           0  vkVSCC7xljjrAI4UGfnKEQ  ...     0    0
1           1  n6QzIUObkYshz4dz2QRJTw  ...     0    0
2           2  MV3CcKScW05u5LVfF6ok0g  ...     0    0
3           3  IXvOzsEMYtiJI0CARmj77Q  ...     0    0
4           4  L_9BTb55X0GDtThi6GlZ6w  ...     0    0

[5 rows x 10 columns]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
Unnamed: 0     10000 non-null int64
review_id      10000 non-null object
user_id        10000 non-null object
business_id    10000 non-null object
stars          10000 non-null int64
date           10000 non-null object
text           10000 non-null object
useful         10000 non-null int64
funny          10000 non-null int64
cool           10000 non-null int64
dtypes: int64(5), object(5)
memory usage: 781.4+ KB


In [31]:
df['stars'].value_counts()

5    3554
4    2966
3    1716
2     891
1     873
Name: stars, dtype: int64

In [0]:
df['classe'] = 1

In [33]:
ind = df[df['stars'] < 4].index
df.loc[ind, 'classe'] = 0

df['classe'].value_counts()

1    6520
0    3480
Name: classe, dtype: int64

In [0]:
indd = random.sample(list(df[df['classe'] == 1].index), (len(df[df['classe'] == 1]) - len(df[df['classe'] == 0])))

In [0]:
df.drop(index=indd, inplace=True)

In [36]:
df['classe'].value_counts()

1    3480
0    3480
Name: classe, dtype: int64

In [37]:
import nltk
nltk.download('stopwords')
stopw = nltk.corpus.stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [88]:
vect = TfidfVectorizer(stop_words=stopw, max_features=12000, ngram_range=(1, 2))
vect

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=12000,
                min_df=1, ngram_range=(1, 2), norm='l2', preprocessor=None,
                smooth_idf=True,
                stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...],
                strip_accents=None, sublinear_tf=False,
                token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
                vocabulary=None)

In [89]:
vect.fit(df['text'])

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=12000,
                min_df=1, ngram_range=(1, 2), norm='l2', preprocessor=None,
                smooth_idf=True,
                stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...],
                strip_accents=None, sublinear_tf=False,
                token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
                vocabulary=None)

In [81]:
vect.vocabulary_

{'super': 6819,
 'simple': 6351,
 'place': 5195,
 'amazing': 285,
 'nonetheless': 4692,
 'around': 406,
 'since': 6355,
 '30': 57,
 'still': 6706,
 'serve': 6171,
 'thing': 7055,
 'started': 6661,
 'salami': 5991,
 'sandwich': 6021,
 'mustard': 4552,
 'staff': 6618,
 'helpful': 3370,
 'friendly': 2802,
 'place amazing': 5198,
 'staff helpful': 6622,
 'helpful friendly': 3371,
 'small': 6422,
 'changes': 1191,
 'menu': 4354,
 'every': 2294,
 'often': 4767,
 'cool': 1555,
 'decor': 1822,
 'vibe': 7533,
 'inside': 3608,
 'seat': 6109,
 'restaurant': 5824,
 'call': 1032,
 'reservation': 5808,
 'beef': 682,
 'tartar': 6950,
 'pork': 5347,
 'belly': 705,
 'start': 6658,
 'salmon': 5997,
 'dish': 1982,
 'lamb': 3815,
 'meal': 4304,
 'mains': 4197,
 'everything': 2307,
 'incredible': 3576,
 'could': 1584,
 'go': 2997,
 'length': 3905,
 'listed': 3994,
 'ingredients': 3597,
 'really': 5650,
 'make': 4205,
 'dishes': 1985,
 'honestly': 3440,
 'need': 4584,
 'bit': 770,
 'outside': 4916,
 'downto

In [90]:
repx = vect.transform(df['text'])
repx = repx.toarray()

repx[:2]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [91]:
len(vect.vocabulary_)

12000

In [92]:
X = repx
y = np.array(df['classe'])

X, y

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]), array([1, 1, 1, ..., 0, 0, 1]))

In [0]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(300, activation='relu', input_shape=(len(vect.vocabulary_),), kernel_regularizer=tf.keras.regularizers.l2(0.01)),
  tf.keras.layers.Dense(200, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

In [0]:
model.compile(optimzer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [103]:
hist = model.fit(X, y, validation_split=0.2,epochs=15)

Train on 5568 samples, validate on 1392 samples
Epoch 1/15
5568/5568 [==============================] - 6s 1ms/sample - loss: 1.0955 - accuracy: 0.5449 - val_loss: 0.7039 - val_accuracy: 0.5481
Epoch 2/15
5568/5568 [==============================] - 5s 949us/sample - loss: 0.7077 - accuracy: 0.6363 - val_loss: 0.7008 - val_accuracy: 0.7608
Epoch 3/15
5568/5568 [==============================] - 5s 958us/sample - loss: 0.6915 - accuracy: 0.7717 - val_loss: 0.6481 - val_accuracy: 0.8103
Epoch 4/15
5568/5568 [==============================] - 5s 949us/sample - loss: 0.6610 - accuracy: 0.7922 - val_loss: 0.6293 - val_accuracy: 0.8046
Epoch 5/15
5568/5568 [==============================] - 5s 930us/sample - loss: 0.6404 - accuracy: 0.7960 - val_loss: 0.6137 - val_accuracy: 0.8118
Epoch 6/15
5568/5568 [==============================] - 5s 927us/sample - loss: 0.6215 - accuracy: 0.8078 - val_loss: 0.5946 - val_accuracy: 0.8068
Epoch 7/15
5568/5568 [==============================] - 5s 919us/s

In [105]:
model.predict(vect.transform(['Very good. Amazing place']).toarray()) # A good phrase
model.predict(vect.transform(['This place is boring, terrible.']).toarray()) # A bad phrase

array([[0.02783093]], dtype=float32)