<a href="https://colab.research.google.com/github/douglasbarbosadelima/Data-Science/blob/master/reg_logistic_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regressão logística_2

In [0]:
import pandas as pd
import numpy as np
import math
from sklearn.linear_model import LogisticRegression

In [0]:
df=pd.read_csv('https://raw.githubusercontent.com/douglasbarbosadelima/Data-Science/master/banknotes.txt',names=['f1','f2','f3','f4','fraude'])

In [3]:
df.head()

f1      f2      f3       f4  fraude
0  3.62160  8.6661 -2.8073 -0.44699       0
1  4.54590  8.1674 -2.4586 -1.46210       0
2  3.86600 -2.6383  1.9242  0.10645       0
3  3.45660  9.5228 -4.0112 -3.59440       0
4  0.32924 -4.4552  4.5718 -0.98880       0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
f1        1372 non-null float64
f2        1372 non-null float64
f3        1372 non-null float64
f4        1372 non-null float64
fraude    1372 non-null int64
dtypes: float64(4), int64(1)
memory usage: 53.7 KB


A amostra é balanceada em positivos e negativos? Dica: use .value_counts() na série do target

In [5]:
df['fraude'].value_counts()

0    762
1    610
Name: fraude, dtype: int64

In [13]:
#Montar matriz X e y
X = np.zeros((len(df), 4))
X[:, 0] = df['f1']
X[:, 1] = df['f2']
X[:, 2] = df['f3']
X[:, 3] = df['f4']
y = df['fraude']

X[:2]

array([[ 3.6216 ,  8.6661 , -2.8073 , -0.44699],
       [ 4.5459 ,  8.1674 , -2.4586 , -1.4621 ]])

In [14]:
#criar o classificador
lr = LogisticRegression()
lr

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
#Treinar
lr.fit(X, y)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
#predição
ye = lr.predict(X)

In [17]:
#Acurácia
certos = 0
for i in range(len(y)):
  if int(ye[i]) == int(y[i]): certos += 1
print(certos/len(y)) 

0.9905247813411079


In [19]:
#coeficientes
lr.intercept_, lr.coef_

(array([3.21217099]),
 array([[-3.06415839, -1.75008125, -2.1082241 , -0.15533781]]))

0.9905247813411079
