<a href="https://colab.research.google.com/github/douglasbarbosadelima/Data-Science/blob/master/Scalers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scalers

In [0]:
import numpy as np
import math

In [0]:
f=np.array([2,1,5,-20,2,4])

In [3]:
max=f.max()
min=f.min()
min,max

(-20, 5)

Vamos colocar a feature f na escala de 0 a 1

In [8]:
fs = (f - min) / (max - min)
f,fs

(array([  2,   1,   5, -20,   2,   4]),
 array([0.88, 0.84, 1.  , 0.  , 0.88, 0.96]))

Agora vamos colocar na escala min-max genérica (no caso, min-1, max=1)

In [12]:
range = 2
min = -1
fs2 = fs * range + min
fs2

array([ 0.76,  0.68,  1.  , -1.  ,  0.76,  0.92])

Vamos agora criar a função scale_minmax(f,min,max) que retorna uma cópia de f na nova escala

In [17]:
def scale_minmax(f, min, max):
  mi = f.min()
  ma = f.max()
  return ((f - mi) / (ma - mi)) * (max - min) + min

f48 = scale_minmax(f, 4, 8)
f, f48

(array([  2,   1,   5, -20,   2,   4]),
 array([7.52, 7.36, 8.  , 4.  , 7.52, 7.84]))

In [28]:
fmm=scale_minmax(f,-1,1)
fmm

array([ 0.76,  0.68,  1.  , -1.  ,  0.76,  0.92])

Agora vamos fazer uma versão standardized de f, fs

In [25]:
med = f.mean()
dp = f.std()
fstd = (f - med) / dp

f, fstd

(array([  2,   1,   5, -20,   2,   4]),
 array([ 0.34874292,  0.23249528,  0.69748583, -2.20870514,  0.34874292,
         0.58123819]))

Finalmente, vamos comparar os "scalers" em um gráfico

In [32]:
import matplotlib.pyplot as plt
plt.plot(fmm,[1 for i in range(len(fmm))],'bo')
plt.plot(fstd,[-1 for i in range(len(fmm))],'ro')
plt.show()

TypeError: ignored